### ISSUE TITLE
 Not worked as expected when process 'a280.tsp' due to space

### ISSUE THREAD

**Issue by luohc2004** [tsartsaris/TSPLIB-python-parser#1]
Nodes like " 77   8  49" " 78   8  41" has multiple space in coord, so that the 'partition' method works not as expectation.

**Comment by tsartsaris** [comment]
Try again and let me know the exact error

**Comment by tsartsaris** [comment]
> Nodes like " 77 8 49" " 78 8 41" has multiple space in coord, so that the 'partition' method works not as expectation.

Fixed in the new version after refactoring.
